version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: okestro1
    volumes:
      - /Users/okestro/IdeaProjects/mission1/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - /Users/sangmin/Local/GitHub/okestro-mission1/init.sql:/docker-entrypoint-initdb.d/init.sql