version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: okestro1
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
