services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: okestro1
      MYSQL_DATABASE: mission1

#  vault:
#    image: hashicorp/vault:1.14.1
#    container_name: vault
#    ports:
#      - "8200:8200"
#    cap_add:
#      - IPC_LOCK
#    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: okestro1
#      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
#      VAULT_ADDR: "http://0.0.0.0:8200"
#      VAULT_API_ADDR: "http://127.0.0.1:8200"
#      command: server -dev