spring:
  application:
    name: mission1

  web:
    resources:
      add-mappings: false

  config:
    import: vault://secret/mission1/db

  cloud:
    vault:
      authentication: token
      token: okestro1
      uri: http://localhost:8200
      enabled: true
      fail-fast: true
      
      kv:
        enabled: true
        backend: secret
        default-context: mission1/db


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username:  ${username}
    url: ${url}
    password: ${password}

  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true


  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
