spring:
  application:
    name: mission1

  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: ${driver-class-name}
    username:  ${username}
    url: ${url}
    password: ${password}

  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true


  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
